version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16
    container_name: studant_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - studant-network

  # Serviço do Back-end (API)
  backend:
    build:
      context: ../Back-end
      dockerfile: Dockerfile
    container_name: studant_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/studant_db
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/students" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - studant-network

  # Serviço do Front-end (Nginx)
  frontend:
    build:
      context: ../Front-End
      dockerfile: Dockerfile
    container_name: studant_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - studant-network

networks:
  studant-network:
    driver: bridge

volumes:
  pgdata:
